### ISSUE TITLE
Which the cell will be unlocked and why?

### ISSUE THREAD

**Issue by Rbchi** [jjyr/DCKB#1]
> NervosDAO withdrawal must be completed within 42 epochs(~ 7 days) since the withdrawal started; otherwise, anyone can unlock the cell.

I am not sure why there is the limitation when this idea implemented, could you explained more ?
I love this idea so much!

**Comment by jjyr** [comment]
Good question! I write a document to explain this https://github.com/jjyr/DCKB/wiki/Half-withdrawal

**Comment by Rbchi** [comment]
Many thanks,could I translate it into Chinese?

**Comment by jjyr** [comment]
Sure.
